name: Build Electron App and Provide Download

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20.19.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'

    - name: Install dependencies
      run: npm install

    - name: Build Electron App
      run: npm run electron:build -- --publish=never

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: electron-build
        path: |
          dist/
          dist-electron/
          release/
